version: '3.8'
   services:
     database:
       image: mysql:8.0
       container_name: company_db
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: company
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql
        - ./company.sql:/docker-entrypoint-initdb.d/company.sql
 
    app:
      build: .
      container_name: company_app
      depends_on:
        - database
      ports:
        - "8080:8080"
      environment:
        DB_HOST: database
        DB_PORT: 3306
        DB_NAME: company
        DB_USER: user
        DB_PASSWORD: password
 
  volumes:
    db_data:
 